// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local', override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["TURSO_DATABASE_URL"] ? `${process.env["TURSO_DATABASE_URL"]}?authToken=${process.env["TURSO_AUTH_TOKEN"]}` : "file:./dev.db",
  },
});
